### ISSUE TITLE
Sweep: Write unit tests for `./src/todo/api.rs`.

### ISSUE THREAD

**Issue by sinsky** [sinsky/jsonplaceholder-for-rust#2]
### Details
Write unit tests for `./src/todo/api.rs`.
Test each function in the file. Make sure to test edge cases.

<details open>
<summary>Checklist</summary>

- [X] Modify `Cargo.toml` ✓ https://github.com/sinsky/jsonplaceholder-for-rust/commit/c31e9406b156789e50be93b13994da682ea83e84 [Edit](https://github.com/sinsky/jsonplaceholder-for-rust/edit/sweep/write_unit_tests_for_srctodoapirs/Cargo.toml)
- [X] Running GitHub Actions for `Cargo.toml` ✓  [Edit](https://github.com/sinsky/jsonplaceholder-for-rust/edit/sweep/write_unit_tests_for_srctodoapirs/Cargo.toml)
- [X] Modify `src/todos/api.rs` ✓ https://github.com/sinsky/jsonplaceholder-for-rust/commit/fcd78635e12ea2ce4047c7ccd40563e3f07c42ba [Edit](https://github.com/sinsky/jsonplaceholder-for-rust/edit/sweep/write_unit_tests_for_srctodoapirs/src/todos/api.rs#L86-L118)
- [X] Running GitHub Actions for `src/todos/api.rs` ✓  [Edit](https://github.com/sinsky/jsonplaceholder-for-rust/edit/sweep/write_unit_tests_for_srctodoapirs/src/todos/api.rs#L86-L118)
</details>
